# Generated by Django 3.2.8 on 2021-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Registration_Number', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_Of_Admission', models.DateField()),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Last_Modified_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
