# Generated by Django 3.2.8 on 2021-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentslist',
            name='Id',
        ),
        migrations.AlterField(
            model_name='studentslist',
            name='Created_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
