# Generated by Django 3.2.8 on 2021-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211017_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentslist',
            name='id',
        ),
        migrations.AddField(
            model_name='studentslist',
            name='Id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
