# Generated by Django 3.2.8 on 2021-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211019_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentslist',
            name='id',
            field=models.CharField(default='1', max_length=20, primary_key=True, serialize=False),
        ),
    ]
