# Generated by Django 3.2.8 on 2022-01-08 13:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentslist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('English', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studentsinfo',
            fields=[
                ('id', models.CharField(default='1', max_length=20)),
                ('Roll_No', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('School', models.CharField(max_length=20)),
                ('Mobile', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Address', models.CharField(max_length=50)),
                ('Created_Date', models.DateField(auto_now=True)),
                ('Last_Modified_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentslist',
        ),
    ]
