# Generated by Django 3.2.8 on 2022-01-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20220108_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademics',
            name='Roll_No',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.studentsinfo'),
            preserve_default=False,
        ),
    ]
