# Generated by Django 3.2.8 on 2022-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentacademics_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
    ]
