# Generated by Django 3.2.8 on 2022-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentsinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
