# Generated by Django 3.2.8 on 2022-01-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentsinfo_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsinfo',
            old_name='FirstName',
            new_name='Name',
        ),
    ]
