# Generated by Django 3.2.8 on 2022-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_firstname_studentsinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinfo',
            name='id',
        ),
    ]
