# Generated by Django 3.2.8 on 2022-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_studentsinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='Created_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='Last_Modified_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
