# Generated by Django 3.2.8 on 2022-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20220109_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinfo',
            name='Created_Date',
        ),
        migrations.RemoveField(
            model_name='studentsinfo',
            name='Last_Modified_Date',
        ),
    ]
